name: Go
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    name: Go ${{ matrix.go }}
    strategy:
      matrix:
        go:
        - '1.21.x'
    steps:
    - uses: actions/checkout@v3
    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go }}
    - run: |
        mkdir -p /tmp/src/github.com/xgfone/go-apigateway
        cp -r ./* /tmp/src/github.com/xgfone/go-apigateway
        cd /tmp/src/github.com/xgfone/go-apigateway
        go test -cover -race ./...
